# File: .github/workflows/repo-sync.yml
name: Synchronize
on:
  schedule:
    - cron: '0 0-16,23 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ main ]
  repository_dispatch:
    types: sync-scripts
    
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Synchronize
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "git@gitee.com:lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
